### ISSUE TITLE
2.0.23版本的composer报错

### ISSUE THREAD

**Issue by pandaOreo** [super-eggs/dcat-admin-extensions-distpicker#10]

**Comment by sunkangchina** [comment]
![image](https://user-images.githubusercontent.com/66815206/125965350-ac802861-6352-4d53-b80a-75f54356b499.png)

**Comment by desireluo** [comment]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Fatal error:  Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in D:\git_huohua\dcat_demo\vendor\super-eggs\dcat-admin-extensions-distpicker\src\bootstrap.php:4
Stack trace:
#0 D:\git_huohua\dcat_demo\vendor\composer\autoload_real.php(71): require()
#1 D:\git_huohua\dcat_demo\vendor\composer\autoload_real.php(61): composerRequire15798b2e269a90fcf098f834b71a4621('3b62309afd65065...', 'D:\\git_huohua\\d...')
#2 D:\git_huohua\dcat_demo\vendor\autoload.php(7): ComposerAutoloaderInit15798b2e269a90fcf098f834b71a4621::getLoader()
#3 D:\git_huohua\dcat_demo\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(43): require_once('D:\\git_huohua\\d...')
#4 phar://D:/phpstudy_pro/Extensions/php/php7.3.4nts/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(341): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Event))
#5 phar://D:/phpstudy_pro/Extensions/php/php7.3.4nts/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(220): Composer\EventDispa in D:\git_huohua\dcat_demo\vendor\super-eggs\dcat-admin-extensions-distpicker\src\bootstrap.php on line 4

Fatal error: Uncaught Error: Call to undefined method Dcat\Admin\Admin::extend() in D:\git_huohua\dcat_demo\vendor\super-eggs\dcat-admin-extensions-distpicker\src\bootstrap.php:4
Stack trace:
#0 D:\git_huohua\dcat_demo\vendor\composer\autoload_real.php(71): require()
#1 D:\git_huohua\dcat_demo\vendor\composer\autoload_real.php(61): composerRequire15798b2e269a90fcf098f834b71a4621('3b62309afd65065...', 'D:\\git_huohua\\d...')
#2 D:\git_huohua\dcat_demo\vendor\autoload.php(7): ComposerAutoloaderInit15798b2e269a90fcf098f834b71a4621::getLoader()
#3 D:\git_huohua\dcat_demo\vendor\laravel\framework\src\Illuminate\Foundation\ComposerScripts.php(43): require_once('D:\\git_huohua\\d...')
#4 phar://D:/phpstudy_pro/Extensions/php/php7.3.4nts/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(341): Illuminate\Foundation\ComposerScripts::postAutoloadDump(Object(Composer\Script\Event))
#5 phar://D:/phpstudy_pro/Extensions/php/php7.3.4nts/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(220): Composer\EventDispa in D:\git_huohua\dcat_demo\vendor\super-eggs\dcat-admin-extensions-distpicker\src\bootstrap.php on line 4

**Comment by siYuanJun** [comment]
同上问题！
